sudo: required

language: java

jdk:
 - oraclejdk8

#services:
# - docker

script:
  - chmod +x gradlew
  - ./gradlew bootJar

before_install:
# - docker build -t db_client_app .

install: gradle wrapper

after_success:
 - ./gradlew bootRun
# - docker run db_client_app

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
on:
   branch: master