sudo: required

language: java

jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew

install:
 - gradle wrapper
 - gradle assemble

services: mongodb
# - docker

#before_install:
# - docker pull alexbz/alternate_db_client
# - docker build -f Dockerfile -t db_client_app .
# - docker run -p 8080:8080 db_client_app

deploy:
  provider: pages
  skip-cleanup: true
  file: build/libs/db_client_rest_api-0.1.jar
  github-token: $GITHUB_TOKEN
  keep-history: true
on:
   branch: master