sudo: required

language: java

services:
 - docker

jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew
 - docker pull alexbz/alternate_db_client
 - docker run alexbz/alternate_db_client

install: gradle wrapper

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
on:
   branch: master