#before_script
# - sleep 15
# - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
install: gradle wrapper --gradle-version 4.2
language: java
jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
on:
   branch: master

#TODO: boot on travis hosted on
#script:
# after_success
#- ./gradlew.bat bootRun

