sudo: required

language: java

services:
 - docker

jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew
 - docker build -t db_client_app . --rm=false
 - docker run db_client_app

install: gradle wrapper

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
on:
   branch: master