sudo: required

language: java

jdk:
 - oraclejdk8

services:
 - docker

script:
  - chmod +x gradlew
  - gradle wrapper

before_install:
  - ./gradlew bootJar
 - docker build -f Dockerfile -t db_client_app .

after_success:
 - docker run -p 8080:8080 db_client_app

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
on:
   branch: master